#!/usr/bin/env python3
import json
import base64
from itsdangerous import base64_decode
from yinglish import chs2yin
from discord.ext import commands

with open("config.json", "r", encoding="utf-8") as jfile:
    jdata = json.load(jfile)
bot = commands.Bot(command_prefix=jdata['prefix'])
yin = 0.5


@bot.event
async def on_ready():
    print(">> Bot ready! <<")


@bot.event
async def on_message(message):
    channel = message.channel
    await channel.send(chs2yin(message.content, yin))


@bot.command()
async def sety(ctx, arg):
    try:
        if float(arg) > 0.0 and float(arg) < 1.0:
            ctx.send("Set yin to {}".format(yin))
        else:
            ctx.send("Must be a float (0.0 - 1.0)")
    except:
        ctx.send("Must be a float (0.0 - 1.0)")

bot.run(base64_decode(jdata['token']))
