#!/usr/bin/env python3
import json
from itsdangerous import base64_decode
from yinglish import chs2yin
from discord.ext import commands

with open("config.json", "r", encoding="utf-8") as jfile:
    jdata = json.load(jfile)
bot = commands.Bot(command_prefix=jdata['prefix'])
yin = 0.5


@bot.event
async def on_ready():
    print(">> Bot ready! <<")


@bot.event
async def on_message(message):
    if message.author.bot:
        return
    if message.content.startswith(jdata['prefix']):
        await bot.process_commands(message)
        return
    channel = message.channel
    print("get message {}".format(message.content))
    await channel.send(chs2yin(message.content, yin))


@bot.command()
async def set(ctx, arg):
    print("get arguments {}".format(arg))
    try:
        if float(arg) > 0.0 and float(arg) < 1.0:
            yin = float(arg)
            await ctx.send(chs2yin(("〇乱度被设置成了 {}！！！".format(yin))))
        else:
            await ctx.send(chs2yin("〇乱度必须是一个不大于1的小数！！！！！"))
    except:
        await ctx.send(chs2yin("〇乱度必须是一个不大于1的小数！！！！！"))

bot.run(base64_decode(jdata['token']).decode("utf-8").strip())
