#!/usr/bin/env python3
import discord
from yinglish import chs2yin
from discord.ext import commands

bot = commands.Bot(command_prefix='!')
yin = 0.5

@bot.event
async def on_ready():
    print(">> Bot ready! <<")


@bot.event
async def on_message(message):
    channel = message.channel
    await channel.send(chs2yin(message.content, yin))


@bot.command()
async def sety(ctx, arg):
    try:
        if float(arg) > 0.0 and float(arg) < 1.0:
            ctx.send("Set yin to {}".format(yin))
        else:
            ctx.send("Must be a float (0.0 - 1.0)")
    except:
        ctx.send("Must be a float (0.0 - 1.0)")

bot.run("OTM1ODA1ODIyMjU5MzEwNjEy.YfD_Fg.3oH93ZLMGcsxbs3Or3qeet-r5jg")
